version: 2.1
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Download architect
          command: |
            architect_version="2.1.5"
            curl -fsSL https://github.com/giantswarm/architect/releases/download/v${architect_version}/architect-v${architect_version}-linux-amd64.tar.gz | tar -xzv --strip-components 1 --wildcards '*/architect'
            ./architect version
      - run:
          name: Deploy
          command: |
            ./architect deploy
workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only: master
